# Generated by Django 5.2 on 2025-05-06 09:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Họ')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Tên')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Số điện thoại phải có định dạng: '+999999999'. Tối đa 15 ký tự.", regex='^\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(choices=[('customer', 'Khách hàng'), ('sales_staff', 'Nhân viên bán hàng'), ('inventory_manager', 'Nhân viên quản lý kho'), ('branch_manager', 'Quản lý chi nhánh'), ('business_owner', 'Chủ doanh nghiệp')], default='customer', max_length=20, verbose_name='Vai trò')),
                ('is_staff', models.BooleanField(default=False, help_text='Xác định người dùng có thể đăng nhập vào trang quản trị hay không.', verbose_name='Nhân viên')),
                ('is_active', models.BooleanField(default=True, help_text='Chỉ định người dùng có hoạt động hay không.', verbose_name='Hoạt động')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tham gia')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Đăng nhập lần cuối')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông tin khách hàng',
                'verbose_name_plural': 'Thông tin khách hàng',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('position', models.CharField(max_length=100, verbose_name='Chức vụ')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày tuyển dụng')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='branches.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông tin nhân viên',
                'verbose_name_plural': 'Thông tin nhân viên',
            },
        ),
    ]
