# Generated by Django 5.2 on 2025-05-06 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên kho')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Sức chứa (m²)')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Kho',
                'verbose_name_plural': 'Kho',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True, verbose_name='Mã tham chiếu')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('movement_type', models.CharField(choices=[('in', 'Nhập kho'), ('out', 'Xuất kho'), ('transfer', 'Chuyển kho'), ('adjustment', 'Điều chỉnh'), ('return', 'Trả hàng')], max_length=20, verbose_name='Loại')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Đơn giá')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='inventory.warehouse')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Lịch sử xuất nhập kho',
                'verbose_name_plural': 'Lịch sử xuất nhập kho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng')),
                ('location', models.CharField(blank=True, help_text='Ví dụ: A12, B5, ...', max_length=50, verbose_name='Vị trí')),
                ('min_stock_level', models.PositiveIntegerField(default=5, verbose_name='Mức tồn kho tối thiểu')),
                ('max_stock_level', models.PositiveIntegerField(default=100, verbose_name='Mức tồn kho tối đa')),
                ('last_counted', models.DateTimeField(auto_now=True, verbose_name='Kiểm kê lần cuối')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
