# Generated by Django 5.2 on 2025-05-06 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('report_type', models.CharField(choices=[('sales', 'Báo cáo bán hàng'), ('inventory', 'Báo cáo tồn kho'), ('performance', 'Báo cáo hiệu suất'), ('financial', 'Báo cáo tài chính')], max_length=20, verbose_name='Loại báo cáo')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Các tham số được sử dụng để tạo báo cáo, dạng JSON', verbose_name='Tham số')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu kết quả')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Yêu thích')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Báo cáo',
                'verbose_name_plural': 'Báo cáo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('frequency', models.CharField(choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng'), ('quarterly', 'Hàng quý')], max_length=20, verbose_name='Tần suất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Lần chạy cuối')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Lần chạy kế tiếp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('recipients', models.ManyToManyField(related_name='report_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.report')),
            ],
            options={
                'verbose_name': 'Lịch báo cáo',
                'verbose_name_plural': 'Lịch báo cáo',
                'ordering': ['-created_at'],
            },
        ),
    ]
